servo_control_node:
  ros__parameters:
      enable_drivers: true
      enable_visualization: true
      # 左右臂独立配置
      enable_left_arm: false    # 是否启用左臂
      enable_right_arm: true     # 是否启用右臂
      left_arm_ip: '192.168.3.101'   # 左臂IP地址
      left_gripper_serial_port: "com3"
      left_gripper_serial_enable: false
      right_arm_ip: '192.168.3.100'  # 右臂IP地址
      right_gripper_serial_port: "com2"
      right_gripper_serial_enable: true