from aid_robot_msgs.srv._ai_cmd import AICmd  # noqa: F401
from aid_robot_msgs.srv._arm_control import ArmControl  # noqa: F401
from aid_robot_msgs.srv._control_launch import ControlLaunch  # noqa: F401
from aid_robot_msgs.srv._draw_picture import DrawPicture  # noqa: F401
from aid_robot_msgs.srv._find_best_velocity import FindBestVelocity  # noqa: F401
from aid_robot_msgs.srv._forbidden_get import ForbiddenGet  # noqa: F401
from aid_robot_msgs.srv._forbidden_set import ForbiddenSet  # noqa: F401
from aid_robot_msgs.srv._general_interface import GeneralInterface  # noqa: F401
from aid_robot_msgs.srv._get_current_forbidden import GetCurrentForbidden  # noqa: F401
from aid_robot_msgs.srv._get_current_map import GetCurrentMap  # noqa: F401
from aid_robot_msgs.srv._get_dock_pose import GetDockPose  # noqa: F401
from aid_robot_msgs.srv._get_string import GetString  # noqa: F401
from aid_robot_msgs.srv._map_image import MapImage  # noqa: F401
from aid_robot_msgs.srv._map_linked_data_list import MapLinkedDataList  # noqa: F401
from aid_robot_msgs.srv._map_list import MapList  # noqa: F401
from aid_robot_msgs.srv._map_operation import MapOperation  # noqa: F401
from aid_robot_msgs.srv._map_operation_add import MapOperationAdd  # noqa: F401
from aid_robot_msgs.srv._operation_add import OperationAdd  # noqa: F401
from aid_robot_msgs.srv._operation_delete import OperationDelete  # noqa: F401
from aid_robot_msgs.srv._operation_get import OperationGet  # noqa: F401
from aid_robot_msgs.srv._operation_update import OperationUpdate  # noqa: F401
from aid_robot_msgs.srv._path_nav import PathNav  # noqa: F401
from aid_robot_msgs.srv._patrol_control import PatrolControl  # noqa: F401
from aid_robot_msgs.srv._point_get import PointGet  # noqa: F401
from aid_robot_msgs.srv._pose_nav import PoseNav  # noqa: F401
from aid_robot_msgs.srv._query_launch_status import QueryLaunchStatus  # noqa: F401
from aid_robot_msgs.srv._set_current_map import SetCurrentMap  # noqa: F401
from aid_robot_msgs.srv._set_dock_pose import SetDockPose  # noqa: F401
from aid_robot_msgs.srv._set_string import SetString  # noqa: F401
from aid_robot_msgs.srv._status_change import StatusChange  # noqa: F401
